# Generated by Django 2.1 on 2018-09-10 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.FloatField(default=0, verbose_name='oferta')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('data', models.DateField(auto_now=True, verbose_name='data')),
                ('datafim', models.DateField(verbose_name='data')),
                ('lancemin', models.FloatField(default=0, verbose_name='lance_minimo')),
                ('ofertamax', models.FloatField(default=0, verbose_name='oferta_max')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
        migrations.AddField(
            model_name='oferta',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='mercadolivre.Produto', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user5', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
