# Generated by Django 2.1 on 2018-09-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolivre', '0003_auto_20180910_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data',
        ),
    ]
